name: github-actions-test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: install python requirements
        run: pip3 install -r requirements.txt
      - name: install bats
        run: npm install -g bats
      - name: check bats version
        run: bats -v
      - name: check python version
        run: python --version
      - name: get packages
        run: sudo apt-get -y install tigervnc-standalone-server blackbox xterm libpulse0 command-not-found wget bzip2 xvfb xdotool
      - name: adduser
        run: sudo adduser --gecos 'User Name,,,' --disabled-password user
      - name: download eagle
        run: wget -q -O /tmp/eagle.tar.gz https://www.autodesk.com/eagle-download-lin
      - name: set time zone
        run: sudo ln -sf /usr/share/zoneinfo/UTC /etc/localtime
      - run: sudo apt-get -y install locales
      - run: sudo -i
      # - run: cat /etc/locale.gen
      # - run: echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
      - run: sudo /usr/sbin/locale-gen
      - name: install eagle dependencies
        run: sudo apt-get -y install libnspr4 libglib2.0-0 libnss3 libasound2 man-db
      - name: make eagle folder
        run: mkdir -p /opt/eagle-9.6.2
      - name: chown eagle
        run: sudo chown user:user /opt/eagle-9.6.2
      - run: sudo mkdir -p /home/user/bin
      - name: chown bin
        run: sudo chown -R user:user /home/user/bin
      - run: sudo mv ELECROW_gerber_v9.cam /home/user/ELECROW_gerber_v9.cam
      - run: sudo mv optoSensor.brd /home/user/optoSensor.brd
      - name: unzip
        run: tar zxpf /tmp/eagle.tar.gz
      - run: sudo cp -r eagle-9.6.2 /opt/
      - name: make eagle dir
        run: sudo mkdir /home/user/eagle
      - name: chmod start
        run: chmod +x start.sh
      - name: connect dummy display
        run: ./start.sh
      - name: remove zip
        run: rm /tmp/eagle.tar.gz
      - name: review contents
        run: ls /home/user
      - name: move creds
        run: sudo mv creds.js /home/user
      - name: grant permissions to python file
        run: chmod 777 boms-auto.py
      - name: check contents
        run: ls /home/user
      - run: pip3 install gspread
      - name: run python file
        run: sudo python3 boms-auto.py
        
