name: github-actions-test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: npm install -g bats
      - run: bats -v
      - run: python --version
      - run: cd /
      - run: sudo apt-get update && apt-get -y upgrade
      
